CC=clang

FLAGS = \
	-DENABLE_TRACE \
	-DHOST \
	-I ../ \
	-I ../zmqpp-root/include \
	-Os \
	-Wall \
	-Wextra \
	-Wno-parentheses \
	-Wshadow \
	-Wunreachable-code \
	-fomit-frame-pointer \
	-g

ifndef RELEASE
	FLAGS +=  \
		-fsanitize=address
endif

CXXFLAGS = \
	$(FLAGS) \
	-std=c++14

LDFLAGS = \
	-L ../zmqpp-root/lib \
	-lpthread \
	-lstdc++ \
	-lzmq \
	-lzmqpp

ifndef RELEASE
	LDFLAGS += \
		-fsanitize=address
endif
